# One machine.
#
# Everything here is what the installer asked, or what only this machine can
# know. Anything true of every machine belongs in nixarchy's host module, not
# in a copy of this file.
#
# The directory name is the hostname: ../../flake.nix reads ./hosts to find
# machines, so renaming the directory renames the configuration.
{ inputs, lib, ... }:
{
  imports = [
    # Read from the nixarchy store path rather than copied in, so it tracks the
    # pinned revision instead of going stale here. inputs.self is nixarchy --
    # flake.nix substitutes it in specialArgs.
    (import "${inputs.self}/installer/host.nix" {
      hostname = "@hostname@";
      username = "@username@";
    })

    # Shared between every machine in this repo, because the layout is the same
    # everywhere the installer writes one. A machine that partitions
    # differently gets its own file here instead.
    (import ../../disk-config.nix {
      # "whole", "free" or "existing". "free" means this machine was installed
      # beside another operating system: it describes two partitions by label
      # and no partition table at all, so disko can never rebuild the table
      # from it. "existing" is the Apple Silicon dual boot: it adopts the two
      # partitions the Asahi installer already made (device = the Linux root,
      # esp = the dedicated ESP) and again describes no partition table.
      # Read the header of ../../disk-config.nix before assuming otherwise.
      mode = "@diskmode@";
      device = "@device@";
      # Only meaningfully substituted for mode = "existing"; the other modes
      # ignore it.
      esp = "@espdevice@";
      # Quoted deliberately: the bare token is not valid Nix -- the file would
      # not parse, let alone format -- so the installer substitutes the quotes
      # away along with it. The autologin flag in configuration.nix is quoted
      # for the same reason.
      encrypt = "@encrypt@";
    })

    # What this machine IS, as nixos-hardware modules -- CPU microcode, GPU
    # drivers, fstrim, laptop power. Generated by detecting the hardware at
    # install time (installer/hardware-modules.sh), which is nixarchy's
    # equivalent of Omarchy's install/hardware/ scripts, except that the 439
    # modules behind it are maintained by people who own the machines.
    #
    # A placeholder `{ }` until step 7 of the install, because this file has to
    # parse before there is a mounted disk to detect anything from.
    ./nixarchy-hardware.nix

    ./configuration.nix

    # This fork exists for Apple Silicon: on arm64 the machine cannot boot
    # without m1n1 + U-Boot, so wire nixos-apple-silicon in automatically.
    # A real ``true``/``false``: the installer substitutes "@apple_silicon@"
    # along with its quotes, exactly like @encrypt@. Quoted because a bare
    # token is not parseable Nix, and a module arg in imports is the
    # documented module-system infinite recursion -- so no gating on pkgs.
    # Inert on x86_64. inputs.self is nixarchy, via the specialArgs above.
  ]
  ++ lib.optionals "@apple_silicon@" [
    inputs.self.nixosModules.appleSilicon
  ];
}
